version: '3.8'
services:
  weather:
    image: weather:latest
    ports:
      - "8081"
    depends_on:
      - postgres
      - rabbitmq

  user-management:
    image: user-management:latest
    ports:
      - "8080"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: registry.docker.ir/postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: registry.docker.ir/rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres-data:
