FROM openjdk:17-jdk-slim

WORKDIR /app

COPY . .
RUN ./user-management/mvnw dependency:resolve

RUN ./user-management/mvnw package

ENTRYPOINT ["java", "-jar", "user-management/target/user-management-0.0.1-SNAPSHOT.jar"]