FROM openjdk:17-jdk-slim

WORKDIR /app

COPY ./user-management ./user-management
COPY ./weather ./weather
COPY pom.xml .
COPY ./.mvn ./.mvn

RUN ./user-management/mvnw dependency:resolve

RUN ./user-management/mvnw package

ENTRYPOINT ["java", "-jar", "user-management/target/user-management-0.0.1-SNAPSHOT.jar"]