FROM openjdk:17-jdk-slim

WORKDIR /app

COPY ./weather .
COPY ./.mvn ./.mvn

RUN ./mvnw dependency:resolve

RUN ./mvnw package

ENTRYPOINT ["java", "-jar", "weather/target/weather-0.0.1-SNAPSHOT.jar"]