FROM openjdk:17-jdk-slim

WORKDIR /app

COPY ./user-management .
COPY ./.mvn ./.mvn

RUN ./mvnw dependency:resolve

RUN ./mvnw package

ENTRYPOINT ["java", "-jar", "user-management/target/user-management-0.0.1-SNAPSHOT.jar"]