version: '3.8'
services:
  weather:
    image: weather:latest
    ports:
      - "8081"
    depends_on:
      - postgres
      - rabbitmq

  user-management:
    image: user-management:latest
    ports:
      - "8080"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: authentication
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    depends_on:
      - user-management
      - weather
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres-data:
