### Register User
POST localhost:8081/users/register
Content-Type: application/json

{
  "username": "hasti",
  "password": "asdf"
}

### Test (should be failed)
GET localhost:8081/countries/iran

### Login User
POST localhost:8081/users/login
Content-Type: application/json

{
  "username": "hasti",
  "password": "asdf"
}
> {% client.global.set("auth_token", response.headers.valueOf("Authorization")) %}

### Test (should be successful)
GET localhost:8081/countries/iran
Authorization: {{auth_token}}
